"""Add type column to questions

Revision ID: 06741383d71e
Revises: 
Create Date: 2026-05-01 21:17:31.565915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06741383d71e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
